version: '3.8'

services:
  app:
    image: ${DOCKERHUB_USERNAME}/f1-live-tracker:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped
